language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio update
script:
  - platformio run -e esp12e -e esp01 -e esp01s
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: ".pioenvs/esp01s/firmware.bin"
  skip_cleanup: true
  on:
    tags: true