language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
  - platformio update
script:
  - platformio run -e release -e release_512k
  - mv .pioenvs/release_512/firmware.bin .pioenvs/release/firmware_512k.bin
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: 
    - .pioenvs/release/firmware.bin
    - .pioenvs/release/firmware_512k.bin
  skip_cleanup: true
  on:
    tags: true